from __future__ import annotations

from pathlib import Path
from typing import Sequence

import numpy as np
from netCDF4 import Dataset


def write_temperature_netcdf(
    path: str | Path,
    T: np.ndarray,
    lat: Sequence[float],
    lon: Sequence[float],
) -> None:
    """
    Write final temperature field and coordinates to a NetCDF file.

    Parameters
    ----------
    path : str or Path
        Output NetCDF file path.
    T : np.ndarray
        Temperature field of shape (nlat, nlon) in Kelvin.
    lat : sequence of float
        Latitudes in degrees (length nlat).
    lon : sequence of float
        Longitudes in degrees (length nlon).
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    T = np.asarray(T, dtype="float64")
    lat = np.asarray(lat, dtype="float64")
    lon = np.asarray(lon, dtype="float64")

    if T.ndim != 2:
        raise ValueError("T must be 2D (nlat, nlon)")
    nlat, nlon = T.shape

    if lat.shape[0] != nlat or lon.shape[0] != nlon:
        raise ValueError(
            f"Shape mismatch: T is ({nlat}, {nlon}), "
            f"lat is ({lat.shape[0],}), lon is ({lon.shape[0],})"
        )

    with Dataset(path, mode="w", format="NETCDF4") as ds:
        # Global attributes
        ds.title = "Mini Climate Model (MPI Edition) – Final Temperature Field"
        ds.institution = "Generated by mini-climate-mpi"
        ds.source = "Toy 2D surface temperature diffusion model with MPI"
        ds.history = "Created by write_temperature_netcdf"
        ds.Conventions = "CF-1.8"

        # Dimensions
        ds.createDimension("lat", nlat)
        ds.createDimension("lon", nlon)

        # Coordinate variables
        lat_var = ds.createVariable("lat", "f8", ("lat",))
        lon_var = ds.createVariable("lon", "f8", ("lon",))

        lat_var.units = "degrees_north"
        lat_var.long_name = "latitude"
        lon_var.units = "degrees_east"
        lon_var.long_name = "longitude"

        lat_var[:] = lat
        lon_var[:] = lon

        # Temperature variable
        T_var = ds.createVariable(
            "temperature",
            "f8",
            ("lat", "lon"),
            zlib=True,
            complevel=4,
        )
        T_var.units = "K"
        T_var.long_name = "surface_temperature"
        T_var.standard_name = "air_temperature"
        T_var.coordinates = "lat lon"

        T_var[:, :] = T